[package]
name = "vanadin-tasks"
version = "0.1.0"
edition = "2021"

[dependencies]
rquickjs = { version = "0.4.0", features = ["loader", "dyn-load"] }

log = { workspace = true }
simplelog = { workspace = true }

sysinfo = "0.30.5"
